---
title: "gift_exploration"
output: html_notebook
---

## Load Data
```{r,message=FALSE}
library(tidyverse)
library(ade4)
library(vegan)
library(xfun)
gift <- read_rds("data/GIFT_traits.rds")
```

```{r}
head(gift)
```


## Missing traits
```{r}
miss_traits_gift <- gift %>% 
  select(-species) %>% 
  is.na() %>% 
  colSums() %>% 
  as.data.frame() %>%
  transmute(perc_na = ./nrow(gift) * 100) %>% 
  rownames_to_column(var = "trait") %>% 
  mutate(trait = fct_reorder(trait, perc_na))
```

```{r}
ggplot(miss_traits_gift, aes(perc_na, trait)) +
  geom_bar(stat="identity") +
  labs(x="Percentage of missing data", y="Trait")
```


## Closer look at some traits (most abundant traits)
```{r}
table(gift$Parasite_1)
```
```{r}
table(gift$Photosynthetic_pathway)
```
```{r}
#should we make this ordered?? probably no
table(gift$Growth_form_1)
```
```{r}
table(gift$Growth_form_2)
```
```{r}
table(gift$Life_form_1)
```
```{r}
table(gift$Life_form_2)
```
```{r}
table(gift$Lifecycle_1)
```


## Selection of 7 most abundant traits
```{r}
top_7 <- miss_traits_gift %>% 
  arrange(perc_na) %>% 
  head(7) %>% 
  pull(trait)
```

```{r}
# We decided to remove these two traits since Life_form_2 and Growth_form_2 have more detailed information 
gift_sel_traits <- c("Parasite_1", "Growth_form_2", "Lifecycle_1", "Life_form_1", "Photosynthetic_pathway")
```

```{r}
gift_sel <- gift %>% 
  select(species, all_of(gift_sel_traits)) %>% 
  drop_na()
gift_pcoa <- select(gift_sel, -species)
```


## Calculate gower distance
```{r, message=FALSE}
library(StatMatch)
```
https://gift.uni-goettingen.de/mcmmb/Day8_long_version.html 

```{r}
gift_gower_dist <- gower.dist(gift_pcoa)
```


```{r}
str(gift_pcoa)
```


```{r}
#make a list separating trait based on their category
# continuous
# categorical
# ordinal
#ktab1 <- ktab.list.df(list(gift_pcoa[, 1, drop = FALSE],
#gift_pcoa[, c(2:3)],
#gift_pcoa[, c(4:7)]))

# second argument is the type of traits for each list name
#mat_dissim <- dist.ktab(ktab1, type = c("N", "D", "Q"),
#option = "scaledBYrange") # scaled quantitative traits
```


```{r}
dim(gift_gower_dist)
```


## Run PCoA

1. with package 'ape'
```{r}
#library(ape) # package that provides functions for PCoA
```

```{r}
#pcoa1 <- pcoa(gift_gower_dist) #this is an R session crasher!!
```
```{r}
#biplot.pcoa(pcoa1)
```

```{r}
#plot(pcoa1$vectors[, "Axis.1"], pcoa1$vectors[, "Axis.2"])
```

```{r}
#length(pcoa1$vectors[, "Axis.1"])
```
-> we didn't really know how to visualize the results



2. with package 'stats' from base R
```{r}
# This is cached as it is a slow computation, takes ~1 min on simone computer 
pcoa2 <- cache_rds(cmdscale(gift_gower_dist, eig=TRUE))
 
pcoa2_var_perc <- round(pcoa2$eig/sum(pcoa2$eig)*100, 1) 
```

```{r}
gift_pcoa_compl <- gift_sel %>% 
  mutate(
    pcoa_ax1=pcoa2$points[,1],
    pcoa_ax2=pcoa2$points[,2]
  )
```
```{r}
gift_pcoa_compl
```
```{r}
head(pcoa2_var_perc)
```
```{r}
barplot(head(pcoa2_var_perc))
```


```{r}
ggplot(data=gift_pcoa_compl, aes(pcoa_ax1, pcoa_ax2)) +
  geom_point(alpha=.3) +
  xlab(paste("MDS1 - ", pcoa2_var_perc[1], "%", sep="")) +
  ylab(paste("MDS2 - ", pcoa2_var_perc[2], "%", sep="")) 
```

```{r}
ggplot(data=gift_pcoa_compl, aes(pcoa_ax1, pcoa_ax2, colour = Growth_form_2)) +
  geom_jitter() +
  xlab(paste("MDS1 - ", pcoa2_var_perc[1], "%", sep="")) +
  ylab(paste("MDS2 - ", pcoa2_var_perc[2], "%", sep="")) 
```

we can color by trait
```{r}
ggplot(data=gift_pcoa_compl, aes(pcoa_ax1, pcoa_ax2, colour = Parasite_1)) +
  geom_jitter() +
  xlab(paste("MDS1 - ", pcoa2_var_perc[1], "%", sep="")) +
  ylab(paste("MDS2 - ", pcoa2_var_perc[2], "%", sep="")) 
```

Projects also the categorical variables
```{r}
# ?envfit
ef <- envfit(pcoa2, gift_pcoa)
```

```{r}
ordiplot(pcoa2)
plot(ef, p.max = 0.1)
```

```{r}
table(gift_pcoa$Growth_form_2, gift_pcoa$Photosynthetic_pathway)
```

```{r}
plot(table(gift_pcoa$Growth_form_2, gift_pcoa$Photosynthetic_pathway))
```


# Sourced from Git: PCoA with base R

https://github.com/StatQuest/mds_and_pcoa_demo/blob/master/mds_and_pcoa_demo.R 

```{r}
library(ggplot2)
## In this example, the data is in a matrix called
## data.matrix
## columns are individual samples (i.e. cells)
## rows are measurements taken for all the samples (i.e. genes)
## Just for the sake of the example, here's some made up data...
data.matrix <- matrix(nrow=100, ncol=10)
colnames(data.matrix) <- c(
  paste("wt", 1:5, sep=""),
  paste("ko", 1:5, sep=""))
rownames(data.matrix) <- paste("gene", 1:100, sep="")
for (i in 1:100) {
  wt.values <- rpois(5, lambda=sample(x=10:1000, size=1))
  ko.values <- rpois(5, lambda=sample(x=10:1000, size=1))
 
  data.matrix[i,] <- c(wt.values, ko.values)
}
head(data.matrix)
dim(data.matrix)
 
###################################################################
##
## 1) Just for reference, draw a PCA plot using this data...
##
###################################################################
pca <- prcomp(t(data.matrix), scale=TRUE, center=TRUE) 
 
## calculate the percentage of variation that each PC accounts for...
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var.per
 
## now make a fancy looking plot that shows the PCs and the variation:
pca.data <- data.frame(Sample=rownames(pca$x),
  X=pca$x[,1],
  Y=pca$x[,2])
pca.data
 
ggplot(data=pca.data, aes(x=X, y=Y, label=Sample)) +
  geom_text() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("PCA Graph")
 
###################################################################
##
## 2) Now draw an MDS plot using the same data and the Euclidean
##    distance. This graph should look the same as the PCA plot
##
###################################################################
 
## first, calculate the distance matrix using the Euclidian distance.
## NOTE: We are transposing, scaling and centering the data just like PCA.
distance.matrix <- dist(scale(t(data.matrix), center=TRUE, scale=TRUE),
  method="euclidean")
 
## do the MDS math (this is basically eigen value decomposition)
mds.stuff <- cmdscale(distance.matrix, eig=TRUE, x.ret=TRUE)
 
## calculate the percentage of variation that each MDS axis accounts for...
mds.var.per <- round(mds.stuff$eig/sum(mds.stuff$eig)*100, 1)
mds.var.per
 
## now make a fancy looking plot that shows the MDS axes and the variation:
mds.values <- mds.stuff$points
mds.data <- data.frame(Sample=rownames(mds.values),
  X=mds.values[,1],
  Y=mds.values[,2])
mds.data
 
ggplot(data=mds.data, aes(x=X, y=Y, label=Sample)) +
  geom_text() +
  theme_bw() +
  xlab(paste("MDS1 - ", mds.var.per[1], "%", sep="")) +
  ylab(paste("MDS2 - ", mds.var.per[2], "%", sep="")) +
  ggtitle("MDS plot using Euclidean distance")
 
###################################################################
##
## 3) Now draw an MDS plot using the same data and the average log(fold change)
##    This graph should look different than the first two
##
###################################################################
 
## first, take the log2 of all the values in the data.matrix.
## This makes it easy to compute log2(Fold Change) between a gene in two
## samples since...
##
## log2(Fold Change) = log2(value for sample 1) - log2(value for sample 2)
##
log2.data.matrix <- log2(data.matrix)
 
## now create an empty distance matrix
log2.distance.matrix <- matrix(0,
  nrow=ncol(log2.data.matrix),
  ncol=ncol(log2.data.matrix),
  dimnames=list(colnames(log2.data.matrix),
    colnames(log2.data.matrix)))
 
log2.distance.matrix
 
## now compute the distance matrix using avg(absolute value(log2(FC)))
for(i in 1:ncol(log2.distance.matrix)) {
  for(j in 1:i) {
    log2.distance.matrix[i, j] <-
      mean(abs(log2.data.matrix[,i] - log2.data.matrix[,j]))
  }
}
log2.distance.matrix
 
## do the MDS math (this is basically eigen value decomposition)
## cmdscale() is the function for "Classical Multi-Dimensional Scalign"
mds.stuff <- cmdscale(as.dist(log2.distance.matrix),
  eig=TRUE,
  x.ret=TRUE)
 
## calculate the percentage of variation that each MDS axis accounts for...
mds.var.per <- round(mds.stuff$eig/sum(mds.stuff$eig)*100, 1)
mds.var.per
 
## now make a fancy looking plot that shows the MDS axes and the variation:
mds.values <- mds.stuff$points
mds.data <- data.frame(Sample=rownames(mds.values),
  X=mds.values[,1],
  Y=mds.values[,2])
mds.data
 
ggplot(data=mds.data, aes(x=X, y=Y, label=Sample)) +
  geom_text() +
  theme_bw() +
  xlab(paste("MDS1 - ", mds.var.per[1], "%", sep="")) +
  ylab(paste("MDS2 - ", mds.var.per[2], "%", sep="")) +
  ggtitle("MDS plot using avg(logFC) as the distance")
```

