---
title: "groot test"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


source("Plant_spectrum_functions.R")
```

```{r load, include = FALSE, cache=TRUE}
#source_rmd("paper_reimplentation.Rmd")
```

```{r}
library(tidyverse)
library(psych)
library(FactoMineR)
```

```{r}
groot <- read_rds("data/GRooT_traits_updated_names.rds")
```


```{r}
miss_traits <- groot %>% 
  select(-species) %>% 
  is.na() %>% 
  colSums() %>% 
  as.data.frame() %>%
  transmute(perc_na = ./nrow(groot) * 100) %>% 
  rownames_to_column(var = "trait") %>% 
  mutate(trait = fct_reorder(trait, perc_na))
```

```{r}
ggplot(miss_traits, aes(perc_na, trait)) +
  geom_bar(stat="identity") +
  labs(x="Percentage of missing data", y="Trait")
```
```{r}
top <- head(sort(miss_traits$trait),8)
```
```{r}
groot %>% 
  select(all_of(top)) %>% 
  drop_na() %>% 
  nrow()
```
```{r}
#table(groot$species %in% plants$species)
```

```{r}
top4 <- head(sort(miss_traits$trait),5)
```
```{r}
groot %>% 
  select(all_of(top), -`Root_mycorrhizal colonization` ) %>% 
  drop_na() %>% 
  nrow()
```
```{r}
top
```

```{r}
groot_t4 <- select(groot, all_of(top4), -`Root_mycorrhizal colonization` ) %>% 
  drop_na()
```

```{r}
pairs.panels(groot_t4,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```

```{r}
groot_t4l <- map_df(groot_t4, ~log10(.) %>% scale())
```
```{r}
pairs.panels(groot_t4l,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```


```{r}
pca_t4 <- PCA(groot_t4l)
```
```{r}
plot(pca_t4, label = "none")
```


```{r}
summary(pca_t4)
```


```{r}
groot_sel_traits <- c("Specific_root_length", "Root_N_concentration", "Mean_Root_diameter", "Root_tissue_density")

groot_processed <- groot %>% 
  select(species, all_of(groot_sel_traits)) %>% 
  mutate(across(-species, ~log10(.) %>% scale() %>% as.vector()))

groot %>% 
  select(species, all_of(groot_sel_traits)) %>% 
  mutate(across(-species, ~log10(.) %>% scale() %>% as.vector()  ))
```


```{r}
groot_sel_traits <- c("Specific_root_length", "Root_N_concentration", "Mean_Root_diameter")

groot_processed <- groot %>% 
  select(species, all_of(groot_sel_traits)) %>% 
  mutate(across(-species, ~log10(.) %>% scale() %>% as.vector()))
```


```{r}
pairs.panels(select(groot_processed, -species))
```

```{r}
#write_rds(groot_processed, "data/GRooT_traits_processed.rds")
```



## Check whether Fabaceae are responsible for points in the upper left corner

```{r}
gift_family <- read_rds(here::here("data/GIFT_family.rds"))
str(gift_family)
```

```{r}
gift_family <- gift_family %>%
  mutate(species = paste(genus, species, sep = " "))
length(unique(gift_family$species))
```

```{r}
groot_family <- inner_join(groot, gift_family, by = "species")

top3 <- c("Specific_root_length", "Root_N_concentration", "Mean_Root_diameter", "Root_tissue_density")

groot_t3 <- select(groot_family, all_of(top3)) %>%
  drop_na()

groot_t3l <- map_df(groot_t3, ~log10(.) %>% scale())

pca_t3 <- PCA(groot_t3l)
```


```{r}
pca3_coords <- as.data.frame(pca_t3$ind$coord)

groot_t3_sp <- select(groot_family, all_of(top3), family) %>%
  drop_na()

faba <- ifelse(groot_t3_sp$family == "Leguminosae", "Fabaceae", "other")

ggplot(pca3_coords, aes(Dim.1, Dim.2, colour=faba)) +
  geom_point() +
  scale_color_manual(values = c("Fabaceae" = "green", "other" = "grey"))
```
## Find the species in the upper left corner

```{r}
pca3_coords <- as.data.frame(pca_t3$ind$coord)

groot_t3_sp <- select(groot_family, all_of(top3), family) %>%
  drop_na()

ggplot(pca3_coords, aes(Dim.1, Dim.2)) +
  geom_point()
```
visually selecting the as `Dim2 > 2` and `Dim1 < 1.5`

```{r}
# sp_group <-
```

