---
title: "Merging TRY and GRooT"
output: html_notebook
---
## Load data
```{r, message=FALSE}
library(tidyverse)
```

```{r}
try <- readRDS(here::here("try_corr_names.rds"))
groot <- read.csv(here::here("big_groot_correct_names.csv"))
gift <- readRDS(here::here("20210625_GIFT_traits.rds"))
```

## Merge data sets: try and gift
```{r}
gift_sel_traits <- c("Parasite_1", "Growth_form_2", "Lifecycle_1", "Life_form_1", "Photosynthetic_pathway")

gift_red <- gift %>% 
  select(species, all_of(gift_sel_traits))
```

```{r}
try_red <- try %>% 
  select(-phot_path)
```

```{r}
groot_sel_traits <- c("Specific_root_length", "Root_N_concentration", "Mean_Root_diameter")
groot_red <- groot %>% 
  select(species, all_of(groot_sel_traits))
```


```{r}
gift_try <- inner_join(gift_red, try_red, by = "species")
```


## Compare each column with each other
```{r}
# compares each column with each other to see the pairwise amount of data available
get_amount_data_columnwise <- function(dat, fraction=T){
  dat_pres <- dat %>% 
    transmute(across(-species, negate(is.na)))
  
  amount_data <- map_dfr(names(dat_pres), function(n){
      # each column is compared with every other column
      row <-  map(seq_along(dat_pres), function(i){
        present <- sum(dat_pres[n] & dat_pres[i])
        if (fraction){
           present <- (present / nrow(dat_pres) ) %>% 
              round(2)
        }
        present
      })
      names(row) <- names(dat_pres)
      row
      }
    ) %>% 
   mutate(trait = names(dat_pres)) %>% 
    relocate(trait)
  return(amount_data)
}
```



```{r}
(colwise <- gift_try %>% 
  get_amount_data_columnwise)
```

898 
```{r}
gift_try %>% 
  select(-SSD) %>% 
  drop_na
```

1382
```{r}
gift_try %>% 
  select(-SSD, -Life_form_1) %>% 
  drop_na
```


```{r}
try_gift_groot <- inner_join(groot_red, try_red, by= "species") %>% 
  inner_join(gift_red,  by= "species")
```


```{r}
try_gift_groot %>% 
  select(-SSD, -Life_form_1) %>% 
  drop_na()
```
```{r}
try_gift_groot %>%
  select(-SSD) %>% 
  get_amount_data_columnwise
```
```{r}
try_gift_groot %>% 
  select(-SSD, -LA) %>% 
  drop_na()
```
```{r}
try_gift_groot %>% 
  select(-SSD, -LA, -Mean_Root_diameter) %>% 
  drop_na()
```