---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: online
---

```{r}
library(tidyverse)
library(FactoMineR)
library(missMDA)
library(psych)
```

```{r}
plants_all <- read_rds(here::here("try_diaz_traits_sp_mean.Rds"))

names(plants_all) <- c("species", "LA", "LMA", "N", "phot_path", "H", "SM", "SSD")

#replaces NaN with NAs for consistency later
is.nan.data.frame <- function(x)
  do.call(cbind, lapply(x, is.nan))

plants_all[is.nan(plants_all)] <- NA

# removes NA values
plants <- select(plants_all, -"phot_path") %>% 
  drop_na() %>% 
  filter(SSD>0) # remove platns with 0 SSD

plants_pca <- select(plants, -species) # without species col so can be used in PCA directly
```


# Missing traits
```{r}
miss_traits <- select(plants_all, -species) %>% 
  is.na() %>% 
  colSums() %>% 
  as.data.frame() %>%
  transmute(perc_na = ./nrow(plants_all) * 100) %>% 
  rownames_to_column(var = "trait") %>% 
  mutate(trait = fct_reorder(trait, perc_na))
```
```{r}
ggplot(miss_traits, aes(perc_na, trait)) +
  geom_bar(stat="identity") +
  labs(x="Percentage of missing data", y="Trait")
```
number of NAs per row
```{r}

```


# First look at data

```{r}
pairs.panels(plants_pca,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```

```{r}
pca1 <- PCA(plants_pca)
```


```{r}
plot.PCA(pca1, graph.type="ggplot")
```

# remove outliers
```{r}
arrange(plants, desc(LA)) #remove first four species
```
```{r}
plants_corr <- plants %>%
  filter(!species %in% c("Licania micrantha", "Iriartea deltoidea", "Socratea exorrhiza", "Oenocarpus mapora", "Cecropia insignis"))
```
```{r}
plants_pca2 <- select(plants_corr, -species)

pca2 <- PCA(plants_pca2)

pairs.panels(plants_pca2,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```


# Log transform and normalize data


```{r}
plants3 <- map_df(plants_pca2, ~log10(.) %>% scale())
```

```{r}
pairs.panels(plants3,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```
```{r}
pca3 <- PCA(plants3)
plot.PCA(pca3, label = "none")
```


# divide plants into woody and non-woody plants

```{r}
range(plants$H)
ggplot() +
  geom_histogram(aes(H), data = plants)
```

# take threshold of 1.5m for woody plants

```{r}
#plants3$woody <- ifelse(plants_pca2$H > 1.5, TRUE, FALSE)
#pca4 <- PCA(plants3, quali.sup = 7)
#plot.PCA(pca3, label = "none", habillage = 7)
```
```{r}
pca3_coords <- as.data.frame(pca3$ind$coord)

woody <- ifelse(plants_pca2$H>1.5, "woody", "non-woody")

ggplot(pca3_coords, aes(Dim.1, Dim.2, colour=woody)) +
  geom_point() +
  scale_color_manual(values = c("woody" = "brown", "non-woody" = "green"))
```


```{r}
plants[which(is.infinite(log10(plants$SSD))),]
```

need to remove plants Ajuga reptans and 157 Carex riparia, as the SSD is 0 (updated above)


```{r}

```


```{r}
plot(res.pcs)
```


```{r}
res.pcs <- PCA(res.comp$completeObs)
```


```{r}
pca1 <- PCA(pca_p)
```

```{r}
plot.PCA(pca1, label="none")
```

```{r}
pca1_coords <- as.data.frame(pca1$ind$coord)

woody <- ifelse(plants_pca$H>1.5, "non-woody", "woody")

ggplot(pca1_coords, aes(Dim.1, Dim.2, colour=woody)) +
  geom_point()
```


```{r}
pca1$eig
```

```{r}
ggplot(as.data.frame(pca1$eig), aes(`percentage of variance`)) +
  geom_bar()
```

```{r}
summary(pca1)
```
```{r}
str(pca1)
```

```{r}
 hist(pca1$ind$cos2)
```

```{r}
library(psych)

pairs.panels(pca_p,
density = FALSE, ellipses = FALSE, hist.col = "grey")
```
```{r}
which.max(plants$SM)

plants[522,]
```

```{r}
plants[524,]
```



