---
title: "Merging TRY, Gift and GRooT"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes

---
## Load data
```{r, message=FALSE}
library(tidyverse)
library(StatMatch) # for gower distance
```

```{r}
try <- readRDS(here::here("data/TRY_traits_processed.rds"))
groot <- readRDS(here::here("data/GRooT_traits_processed.rds"))
gift <- readRDS(here::here("data/GIFT_traits.rds"))
```

# Merge data sets: TRY and gift
```{r}
# see other notebook for this selection
gift_sel_traits <- c("Parasite_1", "Growth_form_2", "Lifecycle_1", "Life_form_1", "Photosynthetic_pathway")
gift_red <- gift %>% 
  select(species, all_of(gift_sel_traits))
```

```{r}
groot_sel_traits <- c("Specific_root_length", "Root_N_concentration", "Mean_Root_diameter")
groot_red <- groot %>% 
  select(species, all_of(groot_sel_traits))
```


```{r}
gift_try <- inner_join(gift_red, try, by = "species")
```


### Compare each column with each other
```{r}
# compares each column with each other to see the pairwise amount of data available
get_amount_data_columnwise <- function(dat, fraction=T, perc=T){
  dat_pres <- dat %>% 
    transmute(across(-species, negate(is.na)))
  ncol <- length(dat_pres)
  amount_data <- map_dfr(seq_along(dat_pres), function(i){
      # each column is compared with every other column only with the diagonal
      row <- rep(NA, ncol) # empty column
      for (j in 1:i){
        present <- sum(dat_pres[i] & dat_pres[j])
        if (fraction){
           present <- (present / nrow(dat_pres) ) %>% 
              round(2)
        }
        row[j] <- present
      }
      
      names(row) <- names(dat_pres)
      if (perc) {row <- row * 100} # convert to percentage
      row
      }
    )
  amount_data %>%  
   mutate(trait = names(dat_pres)) %>% 
    relocate(trait)
}
```


```{r}
(colwise <- gift_try %>% 
  get_amount_data_columnwise)
```
```{r}
trait_order <- names(colwise)
colwise %>%   
  gather("trait2", "data", -trait) %>% 
  mutate(
    trait = factor(trait, rev(trait_order)),
    trait2 = factor(trait2, trait_order)
    ) %>% 
  ggplot(aes(trait, trait2, label=data, fill=data)) +
  geom_label() +
  scale_fill_gradient(low="red", high="green") +
  theme(axis.text.x = element_text(angle=30, hjust = 1)) +
  labs(title= "TRY + GIFT", subtitle = "Percentage of data available for each trait combination")
```

## Remove some traits

by removing SSD we have `898` species

```{r}
gift_try %>% 
  select(-SSD) %>% 
  drop_na
```

by removing also `Life_form_1` we have `1382` species

```{r}
gift_try %>% 
  select(-SSD, -Life_form_1) %>% 
  drop_na
```



# Merge all 3 data sets
```{r}
try_gift_groot_all <- inner_join(groot, try, by= "species") %>% 
  inner_join(gift_red,  by= "species")
```

```{r}
try_gift_groot_all
```

## Compare columns again
```{r}
(colwise2 <- try_gift_groot_all %>% 
  get_amount_data_columnwise)
```

```{r}
trait_order2 <- names(colwise2)
colwise2 %>%   
  gather("trait2", "data", -trait) %>% 
  mutate(
    trait = factor(trait, rev(trait_order2)),
    trait2 = factor(trait2, trait_order2)
    ) %>% 
  ggplot(aes(trait, trait2, label=data, fill=data)) +
  geom_label() +
  scale_fill_gradient(low="red", high="green") +
  theme(axis.text.x = element_text(angle=30, hjust = 1)) +
  labs(title= "All datasets", subtitle = "Percentage of data available for each trait combination")
```

## Remove some traits


```{r}
try_gift_groot_all %>% 
  select(-SSD, -Life_form_1) %>% 
  drop_na()
  
# 240 species
```



```{r}
try_gift_groot_all %>% 
  select(-SSD, -LA) %>% 
  drop_na() 
# 193 species
```
```{r}
try_gift_groot_all %>% 
  select(-SSD, -LA, -Mean_Root_diameter) %>% 
  drop_na() 
# 265 species
```


we decide to remove SSD and LA

```{r}
try_gift_groot <- try_gift_groot_all %>% 
  select(-SSD, -LA) %>% 
  drop_na()
```

```{r}
str(try_gift_groot)
```

```{r}
try_gift_groot <- try_gift_groot %>% 
  mutate(across(where(is.numeric), as.vector))
```

```{r}
str(try_gift_groot)
```


```{r}
# tgg stands for Try Gift Groot
tgg_pcoa <- try_gift_groot %>% select(-species)
```


```{r}
tgg_dist <- tgg_pcoa %>%
  select(!where(is.numeric)) %>% 
  gower.dist()
```
```{r}
tgg_pcoa
```

```{r}
gift_red %>% 
  select(-species) %>% 
  drop_na() 
```
```{r}
should_work <- tgg_pcoa %>%
  select(!where(is.numeric)) 
```

```{r}
tgg_pcoa %>% 
  as.data.frame() %>% 
  gower.dist()
```
```{r}
outer
```
```{r}
class(try_gift_groot)
```
```{r}
class(gift_red)
```


```{r}
gift_red %>% 
  select(-species) %>% 
  drop_na() %>% 
  head(100) %>% 
  gower.dist()
```
```{r}
gift_red %>% 
  select(-species) %>% 
  drop_na() %>% 
  gower.dist() 
```


```{r}
library(psych)
```

```{r}
pairs.panels(tgg_pcoa[,1:5])
```

```{r}
tgg_
```


