---
title: "TRY_GIFT_GRooT_separated_growthform"
output: html_notebook
---

```{r setup, include=FALSE}
library(readr)
library(stringr)
source_rmd <- function(file_path) {
  stopifnot(is.character(file_path) && length(file_path) == 1)
  .tmpfile <- tempfile(fileext = ".R")
  .con <- file(.tmpfile) 
  on.exit(close(.con))
  full_rmd <- read_file(file_path)
  codes <- str_match_all(string = full_rmd, pattern = "```(?s)\\{r[^{}]*\\}\\s*\\n(.*?)```")
  stopifnot(length(codes) == 1 && ncol(codes[[1]]) == 2)
  codes <- paste(codes[[1]][, 2], collapse = "\n")
  writeLines(codes, .con)
  flush(.con)
  cat(sprintf("R code extracted to tempfile: %s\nSourcing tempfile...", .tmpfile))
  source(.tmpfile)
}

```

```{r}
source_rmd("TRY_Gift_GRooT_analysis.Rmd")
```

# With trees

```{r}
tgg_tree <- try_gift_groot %>% 
  filter(Growth_form_2 == "tree")
head(tgg_tree)
```

```{r}
# tgg stands for Try Gift Groot
tgg_tree_pcoa_data <- tgg_tree %>% select(-species)
```


```{r}
tgg_tree_dist <- tgg_tree_pcoa_data %>% 
  as.data.frame() %>% 
  gower.dist()
```

```{r}
tgg_tree_pcoa <- cmdscale(tgg_tree_dist, eig=TRUE)
```

```{r}
tgg_tree_pcoa_var <- round(tgg_tree_pcoa$eig/sum(tgg_tree_pcoa$eig)*100, 1)
```


```{r}
tgg_tree_with_pcoa <- tgg_tree %>% 
  mutate(
    pcoa_ax1=tgg_tree_pcoa$points[,1],
    pcoa_ax2=tgg_tree_pcoa$points[,2]
  )
```


```{r}
ggplot() +
  geom_bar(aes(x=head(tgg_tree_pcoa_var) %>% as.factor(), y = head(tgg_tree_pcoa_var)), stat = "identity")
```


Trying to plot the axis and the categories
```{r}
library(vegan)
```


```{r}

tgg_tree_pcoa_data_new_names <- tgg_tree_pcoa_data %>% 
  rename_with(function(col) {paste0(col, "__")}, where(is.character))

tgg_tree_evfit <- envfit(tgg_tree_pcoa, tgg_tree_pcoa_data_new_names)
```
```{r}
tgg_tree_evfit
```

```{r}
corr_coef <- 3.5 # This is to make sure that in the plot the arrows looks similar to the points range
tgg_tree_vectors <- 
  tgg_tree_evfit$vectors$arrows %>%
  as.data.frame() %>% 
  add_rownames("trait") %>% 
  mutate(
    Dim1 = Dim1 / corr_coef,
    Dim2 = Dim2 / corr_coef
  )
```


```{r}
add_origins <- function(dat){
  tibble(
    trait = dat$trait,
    Dim1 = 0,
    Dim2 = 0
  ) %>% 
    bind_rows(dat)
}
```


```{r}
tgg_tree_vectors_pos <- tgg_tree_vectors %>% 
  filter(Dim1 > 0) %>% 
  add_origins()
tgg_tree_vectors_neg <- tgg_tree_vectors %>% 
  filter(Dim1 < 0) %>% 
  add_origins()
```


```{r}
ggplot() +
  geom_line(aes(x= Dim1, y = Dim2, group = trait), data = tgg_tree_vectors_pos, arrow=arrow()) +
  geom_line(aes(x= Dim1, y = Dim2, group = trait), data = tgg_tree_vectors_neg, arrow=arrow(ends = "first")) +
  geom_label(aes(x=Dim1, y=Dim2, label=trait), data=tgg_tree_vectors) +
  geom_point(aes(pcoa_ax1, pcoa_ax2), alpha=.3, data=tgg_tree_with_pcoa) +
  xlab(paste("PCoA ax 1 - ", tgg_tree_pcoa_var [1], "%", sep="")) +
  ylab(paste("PCoA ax 2 - ", tgg_tree_pcoa_var [2], "%", sep="")) 
```


# Without trees

```{r}
tgg_ntree <- try_gift_groot %>% 
  filter(Growth_form_2 != "tree")
head(tgg_ntree)
```

```{r}
# tgg stands for Try Gift Groot
tgg_ntree_pcoa_data <- tgg_ntree %>% select(-species)
```


```{r}
tgg_ntree_dist <- tgg_ntree_pcoa_data %>% 
  as.data.frame() %>% 
  gower.dist()
```

```{r}
tgg_ntree_pcoa <- cmdscale(tgg_ntree_dist, eig=TRUE)
```

```{r}
tgg_ntree_pcoa_var <- round(tgg_ntree_pcoa$eig/sum(tgg_ntree_pcoa$eig)*100, 1)
```


```{r}
tgg_ntree_with_pcoa <- tgg_ntree %>% 
  mutate(
    pcoa_ax1=tgg_ntree_pcoa$points[,1],
    pcoa_ax2=tgg_ntree_pcoa$points[,2]
  )
```


```{r}
ggplot() +
  geom_bar(aes(x=head(tgg_ntree_pcoa_var) %>% as.factor(), y = head(tgg_ntree_pcoa_var)), stat = "identity")
```


Trying to plot the axis and the categories
```{r}
library(vegan)
```


```{r}

tgg_ntree_pcoa_data_new_names <- tgg_ntree_pcoa_data %>% 
  rename_with(function(col) {paste0(col, "__")}, where(is.character))

tgg_ntree_evfit <- envfit(tgg_ntree_pcoa, tgg_ntree_pcoa_data_new_names)
```
```{r}
tgg_ntree_evfit
```

```{r}
corr_coef <- 3.5 # This is to make sure that in the plot the arrows looks similar to the points range
tgg_ntree_vectors <- 
  tgg_ntree_evfit$vectors$arrows %>%
  as.data.frame() %>% 
  add_rownames("trait") %>% 
  mutate(
    Dim1 = Dim1 / corr_coef,
    Dim2 = Dim2 / corr_coef
  )
```


```{r}
add_origins <- function(dat){
  tibble(
    trait = dat$trait,
    Dim1 = 0,
    Dim2 = 0
  ) %>% 
    bind_rows(dat)
}
```


```{r}
tgg_ntree_vectors_pos <- tgg_ntree_vectors %>% 
  filter(Dim1 > 0) %>% 
  add_origins()
tgg_ntree_vectors_neg <- tgg_ntree_vectors %>% 
  filter(Dim1 < 0) %>% 
  add_origins()
```


```{r}
ggplot() +
  geom_line(aes(x= Dim1, y = Dim2, group = trait), data = tgg_ntree_vectors_pos, arrow=arrow()) +
  geom_line(aes(x= Dim1, y = Dim2, group = trait), data = tgg_ntree_vectors_neg, arrow=arrow(ends = "first")) +
  geom_label(aes(x=Dim1, y=Dim2, label=trait), data=tgg_ntree_vectors) +
  geom_point(aes(pcoa_ax1, pcoa_ax2), alpha=.3, data=tgg_ntree_with_pcoa) +
  xlab(paste("PCoA ax 1 - ", tgg_ntree_pcoa_var [1], "%", sep="")) +
  ylab(paste("PCoA ax 2 - ", tgg_ntree_pcoa_var [2], "%", sep="")) 
```


## THE END

```{r}
celebrations()
```

